import { createHash } from "node:crypto";
import {
  linkSync,
  readFileSync,
  unlinkSync,
  writeFileSync
} from "node:fs";
import { fileURLToPath } from "node:url";

export function byteSha256(value: string | Buffer): string {
  return createHash("sha256").update(value).digest("hex");
}

export function canonicalize(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((entry) => canonicalize(entry));
  }
  if (value !== null && typeof value === "object") {
    const record = value as Record<string, unknown>;
    return Object.fromEntries(
      Object.keys(record)
        .sort()
        .map((key) => [key, canonicalize(record[key])])
    );
  }
  return value;
}

export function canonicalSha256(value: unknown): string {
  return byteSha256(JSON.stringify(canonicalize(value)));
}

export function serializeGolden(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

/** Creates a fixture without a rename-overwrite window. */
export function atomicCreateGolden(
  outputUrl: URL,
  bytes: string
): void {
  const outputPath = fileURLToPath(outputUrl);
  const temporaryPath = `${outputPath}.tmp-${process.pid}-${Date.now()}`;
  writeFileSync(temporaryPath, bytes, { flag: "wx" });
  try {
    linkSync(temporaryPath, outputPath);
  } catch (error) {
    if (
      error !== null &&
      typeof error === "object" &&
      "code" in error &&
      error.code === "EEXIST"
    ) {
      throw new Error(
        `Refusing to overwrite frozen fixture ${outputPath}.`
      );
    }
    throw error;
  } finally {
    unlinkSync(temporaryPath);
  }
}

export function readGoldenJson<T>(fixtureUrl: URL): T {
  return JSON.parse(readFileSync(fixtureUrl, "utf8")) as T;
}

export interface ReviewedGoldenGateOptions<T> {
  generated: T;
  fixtureUrl: URL;
  previewFlag: string;
  updateFlag: string;
  reviewedFixtureSha256: string;
  previewSummary: (generated: T, bytes: string) => unknown;
}

/**
 * Preview prints deterministic candidate bytes and never writes. Update is
 * enabled only after the exact SHA is copied into source and creates once.
 */
export function loadPreviewOrCreateReviewedGolden<T>({
  generated,
  fixtureUrl,
  previewFlag,
  updateFlag,
  reviewedFixtureSha256,
  previewSummary
}: ReviewedGoldenGateOptions<T>): T {
  const previewRequested = process.env[previewFlag] === "1";
  const updateRequested = process.env[updateFlag] === "1";
  if (previewRequested && updateRequested) {
    throw new Error("Preview and update modes are mutually exclusive.");
  }

  const bytes = serializeGolden(generated);
  const generatedSha256 = byteSha256(bytes);
  if (previewRequested) {
    process.stdout.write(
      `${JSON.stringify(
        {
          ...((previewSummary(generated, bytes) ?? {}) as object),
          fixtureByteSha256: generatedSha256,
          wroteFixture: false,
          candidate: generated
        },
        null,
        2
      )}\n`
    );
    return generated;
  }

  if (!/^[0-9a-f]{64}$/.test(reviewedFixtureSha256)) {
    throw new Error(
      "Refusing to freeze the Golden until reviewedFixtureSha256 is replaced with the reviewed 64-hex candidate SHA-256."
    );
  }
  if (updateRequested) {
    if (generatedSha256 !== reviewedFixtureSha256) {
      throw new Error(
        `Refusing to write the Golden because its generated bytes do not match the reviewed SHA-256: received ${generatedSha256}.`
      );
    }
    atomicCreateGolden(fixtureUrl, bytes);
    return generated;
  }

  const frozenBytes = readFileSync(fixtureUrl);
  const frozenSha256 = byteSha256(frozenBytes);
  if (frozenSha256 !== reviewedFixtureSha256) {
    throw new Error(
      `Frozen Golden changed: received ${frozenSha256}.`
    );
  }
  const frozen = JSON.parse(frozenBytes.toString("utf8")) as T;
  if (serializeGolden(frozen) !== bytes) {
    throw new Error(
      "Frozen Golden no longer matches the deterministic generated candidate."
    );
  }
  return frozen;
}
